import { useState } from "react";
import { CircuitLayout } from "@/components/CircuitLayout";
import { ToggleSwitch } from "@/components/ToggleSwitch";
import { LEDIndicator } from "@/components/LEDIndicator";
import { TruthTable } from "@/components/TruthTable";

export default function FullAdder() {
  const [inputs, setInputs] = useState({ A: false, B: false, Cin: false });

  const sum = (inputs.A !== inputs.B) !== inputs.Cin;
  const carry = (inputs.A && inputs.B) || (inputs.Cin && (inputs.A !== inputs.B));

  const reset = () => setInputs({ A: false, B: false, Cin: false });

  const truthTableRows = [
    [false, false, false, false, false],
    [false, false, true, true, false],
    [false, true, false, true, false],
    [false, true, true, false, true],
    [true, false, false, true, false],
    [true, false, true, false, true],
    [true, true, false, false, true],
    [true, true, true, true, true],
  ];

  return (
    <CircuitLayout
      title="Full Adder"
      principle="A Full Adder extends the Half Adder by accepting three inputs: A, B, and Carry-in (Cin). It produces Sum and Carry-out (Cout) outputs. This circuit is constructed using two Half Adders and an OR gate. The first Half Adder adds A and B, then the second Half Adder adds that result with Cin. The Carry-out is generated by ORing the carry outputs from both Half Adders. Full Adders are essential for multi-bit addition in digital systems."
      onReset={reset}
      booleanEquations={[
        "Sum = A ⊕ B ⊕ Cin",
        "Cout = (A · B) + (Cin · (A ⊕ B))"
      ]}
      truthTable={
        <TruthTable
          headers={['A', 'B', 'Cin', 'Sum', 'Cout']}
          rows={truthTableRows}
          currentInputs={inputs}
        />
      }
    >
      <div className="grid md:grid-cols-3 gap-8 items-center">
        <div className="space-y-4">
          <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wide">Inputs</h3>
          <ToggleSwitch
            label="A"
            value={inputs.A}
            onChange={(v) => setInputs({ ...inputs, A: v })}
            testId="toggle-input-a"
          />
          <ToggleSwitch
            label="B"
            value={inputs.B}
            onChange={(v) => setInputs({ ...inputs, B: v })}
            testId="toggle-input-b"
          />
          <ToggleSwitch
            label="Cin"
            value={inputs.Cin}
            onChange={(v) => setInputs({ ...inputs, Cin: v })}
            testId="toggle-input-cin"
          />
        </div>

        <div className="flex flex-col items-center gap-4">
          <div className="space-y-2 w-full max-w-xs text-xs text-center text-muted-foreground">
            <div className="px-3 py-2 rounded-md border border-primary/20 bg-card/30">
              Half Adder 1: A ⊕ B
            </div>
            <div className="px-3 py-2 rounded-md border border-primary/20 bg-card/30">
              Half Adder 2: Result ⊕ Cin
            </div>
            <div className="px-3 py-2 rounded-md border border-primary/20 bg-card/30">
              OR Gate: Combines carries
            </div>
          </div>
          <div className="text-center">
            <div className="inline-flex items-center justify-center px-6 py-3 rounded-lg border-2 border-primary/40 bg-card/50 shadow-neon-cyan">
              <span className="text-xl font-bold text-primary">FULL ADDER</span>
            </div>
          </div>
        </div>

        <div className="space-y-4">
          <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wide">Outputs</h3>
          <LEDIndicator label="Sum" value={sum} testId="led-sum" />
          <LEDIndicator label="Cout" value={carry} testId="led-carry" />
        </div>
      </div>
    </CircuitLayout>
  );
}
