import { useState } from "react";
import { CircuitLayout } from "@/components/CircuitLayout";
import { ToggleSwitch } from "@/components/ToggleSwitch";
import { LEDIndicator } from "@/components/LEDIndicator";
import { TruthTable } from "@/components/TruthTable";
import { FullAdderDiagram } from "@/components/FullAdderDiagram";
import { PowerButton } from "@/components/PowerButton";

export default function FullAdder() {
  const [inputs, setInputs] = useState({ A: false, B: false, Cin: false });
  const [powered, setPowered] = useState(true);

  const sum = powered ? ((inputs.A !== inputs.B) !== inputs.Cin) : false;
  const carry = powered ? ((inputs.A && inputs.B) || (inputs.Cin && (inputs.A !== inputs.B))) : false;

  const reset = () => {
    setInputs({ A: false, B: false, Cin: false });
    setPowered(true);
  };

  const truthTableRows = [
    [false, false, false, false, false],
    [false, false, true, true, false],
    [false, true, false, true, false],
    [false, true, true, false, true],
    [true, false, false, true, false],
    [true, false, true, false, true],
    [true, true, false, false, true],
    [true, true, true, true, true],
  ];

  return (
    <CircuitLayout
      title="Full Adder"
      principle="A Full Adder extends the Half Adder by accepting three inputs: A, B, and Carry-in (Cin). It produces Sum and Carry-out (Cout) outputs. This circuit is constructed using two Half Adders and an OR gate. The first Half Adder adds A and B, then the second Half Adder adds that result with Cin. The Carry-out is generated by ORing the carry outputs from both Half Adders. Full Adders are essential for multi-bit addition in digital systems."
      onReset={reset}
      booleanEquations={[
        "Sum = A ⊕ B ⊕ Cin",
        "Cout = (A · B) + (Cin · (A ⊕ B))"
      ]}
      truthTable={
        <TruthTable
          headers={['A', 'B', 'Cin', 'Sum', 'Cout']}
          rows={truthTableRows}
          currentInputs={inputs}
        />
      }
    >
      <div className="space-y-6">
        <div className="flex justify-end">
          <PowerButton powered={powered} onToggle={() => setPowered(!powered)} />
        </div>

        <div className="grid md:grid-cols-3 gap-8 items-center">
          <div className="space-y-4">
            <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wide">Inputs</h3>
            <ToggleSwitch
              label="A"
              value={inputs.A}
              onChange={(v) => setInputs({ ...inputs, A: v })}
              testId="toggle-input-a"
            />
            <ToggleSwitch
              label="B"
              value={inputs.B}
              onChange={(v) => setInputs({ ...inputs, B: v })}
              testId="toggle-input-b"
            />
            <ToggleSwitch
              label="Cin"
              value={inputs.Cin}
              onChange={(v) => setInputs({ ...inputs, Cin: v })}
              testId="toggle-input-cin"
            />
          </div>

          <div className="flex items-center justify-center">
            <FullAdderDiagram
              inputA={inputs.A}
              inputB={inputs.B}
              inputCin={inputs.Cin}
              sum={sum}
              carry={carry}
              powered={powered}
            />
          </div>

          <div className="space-y-4">
            <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wide">Outputs</h3>
            <LEDIndicator label="Sum" value={sum} testId="led-sum" />
            <LEDIndicator label="Cout" value={carry} testId="led-carry" />
          </div>
        </div>
      </div>
    </CircuitLayout>
  );
}
